import type { AppProps } from '@/app/types';
import AppProvider from '@/common/providers/AppProvider';

if (process.env.NODE_ENV === 'development') {
	require('@/mocks');
}

const App = ({ Component, pageProps, emotionCache, err }: AppProps) => {
	return (
		<AppProvider
			emotionCache={emotionCache}
			dehydratedQueryState={pageProps.dehydratedQueryState}
		>
			{/* we need to pass the `err` prop to `Component` in case it's the component generated by `_error.tsx` so it can log the error to sentry if `getInitialProps` is not called. https://github.com/vercel/next.js/issues/8592 */}
			<Component {...pageProps} err={err} />
		</AppProvider>
	);
};

export default App;
